- sample/go/mtgjson.go
As announced in #85:
The very common single string case for set.booster was not handled correctly (sorry - I was to focussed on reading everything without errors and did not check the result enough).
Also, use canonical format by running `go fmt` - convert to tab indentation.
> fix json handling for set.booster

- web/changelog.json
Hey, I'm working on something using mtgjson.com (thanks!) at the moment and noticed that these dates in the changelog were wrong. Perhaps it would be better to just add new objects to the changelog rather than modifying existing ones, but I'll leave that up to you.
> Fixed 2016 changelog dates

- shared/C.js
Fix text repacement rule for Spawnsire of Ulamog which used {1} instead
of {C}.
Also remove some (now) unnecessary Oracle text replacement rules since
the current Oracle text on Gatherer matches the replacement text.
> Fix Oracle text on Spawnsire of Ulamog.

- json/DD3_GVL.json
- json/DDD.json
- json/FUT.json
- json/PLC.json
- json/TOR.json
- json/TSB.json
- json/TSP.json
- json/VMA.json
This fixes #147.
As per Gatherer, these are the sets that have madness:
Vintage Masters VMA
Torment TOR
Duel Decks Garruk vs Lilana DDD / DD3
Planar Chaos PLC
Times Spiral TSP/TSB
Future Sight FUT
Shadows of Innistrad SOI
> update sets that contain madness text

- json/CPK.json
Hero's Downfall in the Clash Pack set has "2" as its number, which is shared with Fated Intervention.
According to magiccards.info [here](http://magiccards.info/query?q=e%3Aclash%2Fen&v=list&s=issue), Hero's Downfall should have 8 as its number instead.
> Fix Clash Pack - Hero's Downfall collector number

- shared/C.js
Using the data I found at http://www.channelfireball.com/articles/whats-the-pick-eldritch-moon-pack-1-pick-1-with-huey/ and http://mtgsalvation.gamepedia.com/Shadows_over_Innistrad I attempted to determine what the booster packs could contain
> Fix SOI & EMN pack contents

- json/EMN.json
- web/documentation.pug
This allows us to deduce which of the three parts of a meld card we're looking at, and refer to a specific other part by indexing the `names` array.
Closes #187.
> Fix names field of meld cards and clarify documentation

- build/rip.js
This patch fixes the `mciNumber` extraction from MCI card URLs.
Currently, many of sets have completely wrong `mciNumber`. Several samples:
```
'4e/en/104',
'4e/en/105',
'4e/en/241',
'5e/en/137',
'5e/en/69',
'5e/en/138',
'/ptc/en/51a.html',
'/ptc/en/51b.html',
'/ptc/en/52a.html',
'/ptc/en/52b.html',
'6e/en/328',
'6e/en/329',
'6e/en/330',
'/fnmp/en/78a.html',
'/fnmp/en/78b.html',
'/fnmp/en/79a.html',
'/fnmp/en/79b.html',
'7e/en/240',
'7e/en/241',
'7e/en/242',
'7e/en/243',
'7e/en/244',
'8e/en/274',
'8e/en/275',
'8e/en/276',
'5dn/en/163',
'5dn/en/164',
'5dn/en/165',
'9e/en/250',
'9e/en/251',
'9e/en/252',
'10e/en/353',
'10e/en/354',
'10e/en/355',
```
You can get such array with this little snippet (running on Node 4.5.0):
```javascript
let _ = require('lodash');
let sets = …
```
> Fix mciNumber extraction

- shared/C.js
This change addresses a bug in the fix for #225.
> Fix Cataclysmic Gearhulk (MPS) wrong multiverseid.

- build/rip.js
- shared/C.js
The latest Gatherer rulings use images for {PW}, {CHAOS} and hybrid mana
symbols.  Some rulings also include HTML ampersands (&amp;) and/or
non-breaking spaces (&nbsp;).  This patch addresses these changes.
> Fixes for errors in Gatherer rulings updates.

- json/EMN.json
Flattens the nested list in the booster data field of EMN, which fixes issue #203
> Fix EMN booster data

- web/documentation.pug
The docs say that the `manaCost` field uses formatting like `GU`, but the actual JSON uses `{G}{U}`.
> Fix mana cost docs

- shared/C.js
For the first time since Morningtide, Magiccards.info has diverged from the official set code, listing `MPS` (Kaladesh Inventions) as `MPSKLD`.
As they do not provide an automatic redirect from (MPS)[http://magiccards.info/mps/en.html] to (MPSKLD)[http://magiccards.info/mpskld/en.html] (As they do with some of the older set code mismatches), I figured it was worth adding the magicCardsInfoCode attribute to this set.
> Add magicCardsInfoCode to Kaladesh Inventions

- shared/C.js
According to the MTG wiki, these sets replace marketing cards, not basic lands, with checklist cards.
> Add checklists to DKA and ORI booster info

- .editorconfig
- .travis.yml
- Test against Ubuntu 14.04 (trusty) instead of 12.04 (precise)
- Test against Node.js 6 (current) instead of 6.1 (mid 2016 version)
- Also test against Node.js 8 (current)
This addresses some flaky errors in build setup.
> Update Travis test environment

- util/clearCacheForSet.js
`async.each` callbacks are only able to receive `err` not results, so passing tiptoe's `this` via `async.each` will always get back 0 URLs.
Here we explicitly pass tiptoe's `this` to the child functions.
> Fix async.each callback for getURL* calls

- .travis.yml
- util/travis.sh
This should make Travis CI fail if a pull request is submitted but does not update the changelog.
Since this pull request does not update the changelog, it will serve as a self-test. I will update the changelog once this test succeeds.
> Add a changelog update check to Travis CI

- web/index.pug
fix #448
no more "Æ"
use other examples instead
> webpage: adjust utf8 text hint

- web/changelog.json
Just noticed the updatedSetFiles section for C17 was missing in the changelog.json.
> Added updatedSetFiles section for C17

- shared/shared.js
Sometimes gatherer has server errors but decides to use http return code 200 (success) instead of 500 (server error). To catch these cases, we match against error messages in the body of the response. This PR adds handling for another error message: "You Just Exploded the Internet."
This should decrease the occurrence of #482 (but probably doesn't solve all of them).
> Ignore "exploded the internet" pages

- json/FUT.json
- json/pPRE.json
- web/changelog.json
- Sultai Ascendancy mana cost was ordered incorrectly compared to other instances in other sets
- Steamflogger Boss was updated as part of Unstable
> some card fixes

- shared/set_configs/RIX.json
- web/changelog.json
follow up to https://github.com/mtgjson/mtgjson/pull/526
cc @DanielHeath: you missed that :)
i don't know about mkm name and id. :(
also missing at all in the files are translations for chinese.
RIX:
- zh-hans (simplified chinese): 决胜依夏兰
- zh-hant (traditional chinese): 決勝依夏蘭
> update translations in rix set info

- json/V17.json
- web/changelog.json
Year of release date was incorrect, see: https://magic.wizards.com/en/products/vault-transform
fixes #550
> Fix release date
