web/changelog.json

Quick spelling correction for mtgjson.com

Spelling correction: s/maintener/maintainer

---

web/changelog.dust
web/documentation.dust
web/index.dust
web/index.pt.dust
web/sets.dust
web/spoiler.dust

Force HTTPS where available.
Increases overall security with no drawbacks.
Apparently my editor also removed some trailing whitespace that was lingering around. If that is a problem I can try to revert and turn that setting off for the project.

Force HTTPS usage.

---

json/WTH.json

This fixes #153. @lsmoura, if you show me how to make all-sets.json, I'm happy to include that in this PR as well. The diff looks to be so large because WTH.json had "mciNumber" which is no longer being exposed.

regenerate Foriysian Brigade text

---

web/documentation.pug

I was importing this data and I found one more expansion type than was mentioned in the docs, should it be added?

Add expansion type

---

web/documentation.pug

Just completing documentation :)

updated docs to contain mciNumber

---

shared/C.js

SOI & EMN Booster Fields

---

json/KLD.json
shared/C.js

Fix "land" slot in Kaladesh

---

web/documentation.pug

sets EXP and MPS are of type `masterpiece`

Add masterpiece to set types in documentation

---

shared/C.js

Also changes tabs to spaces in C.js.

Add story spotlight watermarks

---

shared/C.js

The source for these dates is the [MTG Salvation wiki](http://mtgsalvation.gamepedia.com/), which doesn't provide further sources for most of the dates, so some of them might still be incorrect.

Fix some release dates

---

shared/C.js
shared/shared.js

Add mana symbol watermarks

---

json/C13.json
json/DDH.json
json/PLS.json
json/VMA.json

Nightscape Familiar's ruling is the opposite of what it's supposed to be.

Nightscape familiar ruling

---

web/documentation.pug

Also, I noted that there are several full stops missing, but I didn't want to add them since I don't know this template language and maybe they are used to parse it.

Remove duplicated text

---

shared/C.js
util/clearCacheForSet.js
util/updateLegalitiesFromSet.js

Also updated some requires in `util` dir.

Added AKH to STANDARD_SETS

---

json/AKH.json

Fix issue #354 .
I wanted to fix card name, but some information like "legalities" was added.

Recreate AKH.json

---

.editorconfig
.gitignore
json/.editorconfig
node_modules/.editorconfig
node_modules/.gitignore

Create [EditorConfig](http://editorconfig.org/) configuration for the repo to (hopefully) push us in the direction of common file formatting.

Introduce editorconfig

---

build/rip.js

While fixing an edge case in #368, I introduced a bug that prevents processing of symbols (mana, tap, etc.) from gatherer. The bug was introduced in this line: https://github.com/mtgjson/mtgjson/pull/368/files#diff-b5e97dc43d3c2478dc0c1c266c43c23dR1572
This PR fixes the bug.

Fix processing of mana symbols in text content

---

.travis.yml

- Pre-install unicode-data to prevent install install failures on install of `unicode` from npm
- Enable caching of `node_modules` to speed up module install and compilation of underlying features

Improve CI stability and performance

---

web/_header.pug

website: update link to github

---

.gitignore
cache/0/.gitignore
cache/1/.gitignore
cache/2/.gitignore
cache/3/.gitignore
cache/4/.gitignore
cache/5/.gitignore
cache/6/.gitignore
cache/7/.gitignore
cache/8/.gitignore
cache/9/.gitignore
cache/a/.gitignore
cache/b/.gitignore
cache/c/.gitignore
cache/d/.gitignore
cache/e/.gitignore
cache/f/.gitignore
package.json
shared/shared.js
util/clearCacheForSet.js

- Replace [cache](https://github.com/mtgjson/cache) with [levelup] (https://www.npmjs.com/package/levelup) - fixes #391 
- Use [request](https://www.npmjs.com/package/request) for url fetching
- Do not cache getherer pages with "Server Error" and status code != 200 - fixes #313 
- fix handling of clearCacheForSe with multiple cacheTypes - fixes #390
- refactor document fetching

Replace cache with leveldb and refactor url fetching

---

json/schema/singleSet.schema.json

Fix #71
This will add a schema file for single sets so they can be referenced somewhere, somehow...

Schema file

---

build/rip.js
json/pFNM.json
json/pLPA.json
json/pPRE.json
json/pREL.json
web/changelog.json

fix mciNumber on mci set split cards

---

json/AER.json
json/EMN.json
json/KLD.json
json/OGW.json
shared/shared.js
web/changelog.json

Fix updateStandardForCard to recognize banned cards

---

build/rip.js
json/BNG.json
json/C16.json
json/DDM.json
json/E01.json
json/FRF.json
json/JOU.json
json/KTK.json
json/ME3.json
json/ORI.json
json/PTK.json
json/THS.json
json/pPRE.json
web/changelog.json

strip control characters from card text

---

.travis.yml
package.json
schema/singleSet.schema.json
web/changelog.json

fixes #414 
This is, essentially, a refactor of the excellent work @ZeldaZach started in #421

check json files and validate against schema

---

json/HOU.json
shared/set_configs/HOU.json
web/changelog.json

**Do not release** without fixing the changelog entry.

Add Hour of Devastation story spotlight watermarks

---

README.md

Updates the set description step for the C.js split.

Update instructions for new sets in readme

---

web/index.pug

follow up to https://github.com/mtgjson/mtgjson/pull/393

webpage: link updates

---

web/changelog.json
web/index.js

Only thing I wasn't sure of, is how you would want to handle sets that don't have a block, `UGL` for instance.
I can put whatever you would like there ^_^

Fixes #342 - add block to SetList.json

---

shared/C.js

Per: https://magic.wizards.com/en/content/standard-formats-magic-gathering

update standard sets

---

shared/shared.js

See discussion in #465, thanks to @Psithief for giving the fix.

Fix TypeError while rebuilding

---

json/E02.json
shared/set_configs/games/E02.json
web/changelog.json

Add Explorers of Ixalan

---

README.md

- dynamically pulled from https://mtgjson.com/json/version-full.json
- linking to changelog on website (could also link to changelog file in the repo if one prefer that)
or in blue color: ![](https://img.shields.io/badge/dynamic/json.svg?label=latest%20release&colorB=0d7ebf&prefix=v&query=$.version&uri=https%3A%2F%2Fmtgjson.com%2Fjson%2Fversion-full.json)

readme: show version

---

web/changelog.json

Added updatedSetFiles for RIX.

---

shared/set_configs/ARN.json
shared/set_configs/ATQ.json
shared/set_configs/DRK.json
shared/set_configs/FEM.json
shared/set_configs/RIX.json
shared/set_configs/un/UST.json
web/changelog.json

update booster fields for some sets
Fixes #558 
Fixes #554 
Fixes #547

Lots o Fixes

---

json/DDU.json
shared/set_configs/duel_decks/DDU.json
web/changelog.json

Added DDU, Elves vs. Inventors

---

shared/set_configs/BBD.json
web/changelog.json

Battlebond

---

web/changelog.json
web/documentation.pug

I'm not sure how to add the change to the changelog, sorry.

Add missing possible card layout value
